baseURL = "https://the-khiem7.github.io/SnakeAid.AmazonECS/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "en"
ignoreFiles = ['(?:^|/)_tools(?:/|$)']

theme = "hugo-theme-learn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "workshop"
editURL = ""
description = "Bilingual Hugo outline for documenting Amazon ECS concepts, architecture, deployment, and operations."
author = "thienlh@thienlu.com"
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false

[Languages]
[Languages.en]
title = "Amazon ECS Guide"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "Cẩm Nang Amazon ECS"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
